wiki/plugins/attachments/urls.py
from __future__ import absolute_import, unicode_literals

from django import VERSION as DJANGO_VERSION
from django.conf.urls import patterns, url
from wiki.plugins.attachments import views

urlpatterns = [
    url(r'^$',
        views.AttachmentView.as_view(),
        name='attachments_index'),
    url(r'^search/$',
        views.AttachmentSearchView.as_view(),
        name='attachments_search'),
    url(r'^add/(?P<attachment_id>\d+)/$',
        views.AttachmentAddView.as_view(),
        name='attachments_add'),
    url(r'^replace/(?P<attachment_id>\d+)/$',
        views.AttachmentReplaceView.as_view(),
        name='attachments_replace'),
    url(r'^history/(?P<attachment_id>\d+)/$',
        views.AttachmentHistoryView.as_view(),
        name='attachments_history'),
    url(r'^download/(?P<attachment_id>\d+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^delete/(?P<attachment_id>\d+)/$',
        views.AttachmentDeleteView.as_view(),
        name='attachments_delete'),
    url(r'^download/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^change/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$',
        views.AttachmentChangeRevisionView.as_view(),
        name='attachments_revision_change'),
]

if DJANGO_VERSION < (1, 8):
    urlpatterns = patterns('', *urlpatterns)

wiki/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import VERSION as DJANGO_VERSION
from django.conf.urls import include, url
from wiki.conf import settings
from wiki.core.plugins import registry
from wiki.core.plugins.loader import load_wiki_plugins
from wiki.core.utils import get_class_from_str
from wiki.views import accounts, article, deleted_list


class WikiURLPatterns(object):

    '''
    configurator for wiki urls.

    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view_class = article.ChangeRevisionView
    revision_merge_view = staticmethod(article.merge)

    search_view_class = settings.SEARCH_VIEW
    article_diff_view = staticmethod(article.diff)

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout
    profile_update_view_class = accounts.Update

    # deleted list view
    deleted_list_view_class = deleted_list.DeletedListView

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_deleted_list_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()

        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = [
            url('^$',
                self.article_view_class.as_view(),
                name='root',
                kwargs={'path': ''}),
            url('^create-root/$',
                article.CreateRootView.as_view(),
                name='root_create'),
            url('^missing-root/$',
                article.MissingRootView.as_view(),
                name='root_missing'),
            url('^_search/$',
                get_class_from_str(self.search_view_class).as_view(),
                name='search'),
            url('^_revision/diff/(?P<revision_id>\d+)/$',
                self.article_diff_view,
                name='diff'),
        ]
        return urlpatterns

    def get_deleted_list_urls(self):
        urlpatterns = [
            url('^_admin/$',
                self.deleted_list_view_class.as_view(),
                name="deleted_list"),
        ]
        return urlpatterns

    def get_accounts_urls(self):
        if settings.ACCOUNT_HANDLING:
            urlpatterns = [
                url('^_accounts/sign-up/$',
                    self.signup_view_class.as_view(),
                    name='signup'),
                url('^_accounts/logout/$',
                    self.logout_view_class.as_view(),
                    name='logout'),
                url('^_accounts/login/$',
                    self.login_view_class.as_view(),
                    name='login'),
                url('^_accounts/settings/$',
                    self.profile_update_view_class.as_view(),
                    name='profile_update'),
            ]
        else:
            urlpatterns = []
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = [
            # This one doesn't work because it don't know
            # where to redirect after...
            url(
                '^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url('^_revision/preview/(?P<article_id>\d+)/$',
                self.article_preview_view_class.as_view(),
                name='preview_revision'),
            url(
                '^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$',
                self.revision_merge_view,
                name='merge_revision_preview',
                kwargs={
                    'preview': True}),
        ]
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = [
            # Paths decided by article_ids
            url('^(?P<article_id>\d+)/$',
                self.article_view_class.as_view(),
                name='get'),
            url('^(?P<article_id>\d+)/delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url('^(?P<article_id>\d+)/deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url('^(?P<article_id>\d+)/edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url('^(?P<article_id>\d+)/preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url('^(?P<article_id>\d+)/history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url('^(?P<article_id>\d+)/settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url('^(?P<article_id>\d+)/source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                '^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                '^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url('^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
        ]
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = [
            # Paths decided by URLs
            url('^(?P<path>.+/|)_create/$',
                self.article_create_view_class.as_view(),
                name='create'),
            url('^(?P<path>.+/|)_delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url('^(?P<path>.+/|)_deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url('^(?P<path>.+/|)_edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url('^(?P<path>.+/|)_preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url('^(?P<path>.+/|)_history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url('^(?P<path>.+/|)_dir/$',
                self.article_dir_view_class.as_view(),
                name='dir'),
            url('^(?P<path>.+/|)_settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url('^(?P<path>.+/|)_source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                '^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                '^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url('^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
            # This should always go last!
            url('^(?P<path>.+/|)$',
                self.article_view_class.as_view(),
                name='get'),
        ]
        return urlpatterns

    @staticmethod
    def get_plugin_urls():
        urlpatterns = []
        for plugin in list(registry.get_plugins().values()):
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += [
                    url('^(?P<article_id>\d+)/plugin/' + slug + '/',
                        include(article_urlpatterns)),
                    url('^(?P<path>.+/|)_plugin/' + slug + '/',
                        include(article_urlpatterns)),
                ]
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += [
                    url('^_plugin/' + slug + '/', include(root_urlpatterns)),
                ]
        return urlpatterns


def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if url_config_class is None:
        url_config_classname = getattr(settings, 'URL_CONFIG_CLASS', None)
        if url_config_classname is None:
            url_config_class = WikiURLPatterns
        else:
            url_config_class = get_class_from_str(url_config_classname)
    urlpatterns = url_config_class().get_urls()

    if DJANGO_VERSION < (1, 8):
        from django.conf.urls import patterns

wiki/views/deleted_list.py
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from wiki import models


class DeletedListView(TemplateView):

    template_name = "wiki/deleted_list.html"

    def dispatch(self, request, *args, **kwargs):
        # Let logged in super users continue
        if not request.user.is_superuser:
            return redirect('wiki:root')

        return super(DeletedListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        article_list = models.Article.objects.all()
        deleted_articles = []
        for article in article_list:
            if(article.current_revision.deleted):
                deleted_articles.append(article)
        kwargs['deleted_articles'] = deleted_articles
        context = super(DeletedListView, self).get_context_data(**kwargs)
        return context

wiki/templates/wiki/article.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{{ article.current_revision.title }}{% endblock %}

{% block wiki_breadcrumbs %}
{% include "wiki/includes/breadcrumbs.html" %}
{% endblock %}

{% block wiki_contents %}

  <div id="article-container">
    <ul class="nav nav-pills" id="article-menu">
      <li class="pull-left" id="article-title-li">
        <h1 id="article-title">
          {{ article.current_revision.title }}
          <small style="font-size: 14px;">
            {% if urlpath.parent %}
            <a href="{% url 'wiki:get' path=urlpath.path %}"><span class="fa fa-bookmark"></span> {{ urlpath.slug }}</a>
            {% endif %}
            {% if article.current_revision.locked %}
              <span class="fa fa-lock"></span> {% trans "locked" %}
            {% endif %}
          </small>
        </h1>
      </li>
      {% include "wiki/includes/article_menu.html" %}
    </ul>
    <div>
      {% block wiki_contents_tab %}
      {% endblock %}
    </div>
  </div>

{% endblock %}

{% block wiki_footer_prepend %}
  <p style="margin-bottom: 10px;"><em>{% trans "This article was last modified:" %} {{ article.current_revision.modified }}</em></p>
{% endblock %}

wiki/templates/wiki/base.html
{% extends "wiki/base_site.html" %}

{# Intentionally empty, to allow easy customization with no copy-paste #}

wiki/templates/wiki/dir.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Listing articles in" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% url 'wiki:dir' urlpath.path as self_url %}

<form class="form-search directory-toolbar">
<div class="well well-small">
  <div class="btn-group pull-left">
    {% if urlpath.parent %}
    <a href="{% url 'wiki:dir' path=urlpath.parent.path %}" class="btn btn-default">
      <span class="fa fa-arrow-up"></span>
      {% trans "Up one level" %}
    </a>
    {% endif %}
    <a href="{% url 'wiki:create' path=urlpath.path %}" class="btn btn-default">
      <span class="fa fa-plus"></span>
      {% trans "Add article" %}
    </a>
  </div>
  <div class="pull-right">
    {{ filter_form.query }}
  </div>
  {% if filter_query %}
    <div class="pull-right filter-clear">
      <a href="{{ self_url }}">({% trans "clear" %})</a>
    </div>
  {% endif %}

  <div class="clearfix"></div>
</div>
</form>

<p>
  {% with paginator.object_list.count as cnt %}
    {% blocktrans with urlpath.path as path and cnt|pluralize:_("article,articles") as articles_plur and cnt|pluralize:_("is,are") as articles_plur_verb %}
      Browsing <strong><a href="{{ self_url }}">/{{ path }}</a></strong>. There {{ articles_plur_verb }} <strong>{{ cnt }} {{ articles_plur }}</strong> in this level.
    {% endblocktrans %}
  {% endwith %}
</p>

<table class="table table-striped">
  <tr>
    <th>{% trans "Title" %}</th>
    <th>{% trans "Slug" %}</th>
    <th>{% trans "Last modified" %}</th>
  </tr>
  {% for urlpath in directory %}
    <tr>
      <td>
        <a href="{% url 'wiki:get' path=urlpath.path %}"> {{ urlpath.article.current_revision.title }} </a>
        <a href="{% url 'wiki:dir' path=urlpath.path %}" class="list-children"> › </a>
        {% if urlpath.article.current_revision.deleted %}
          <span class="fa fa-trash"></span>
        {% endif %}
        {% if urlpath.article.current_revision.locked %}
          <span class="fa fa-lock"></span>
        {% endif %}
      </td>
      <td>
        {{ urlpath.slug }}
      </td>
      <td>
        {{ urlpath.article.current_revision.created|naturaltime }}
      </td>
    </tr>
    {% empty%}
    <tr>
      <td colspan="100">
        <em>{% trans "There are no articles in this level" %}</em>
      </td>
    </tr>
  {% endfor %}
</table>

{% include "wiki/includes/pagination.html" %}

{% endblock %}

wiki/templates/wiki/edit.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{% trans "Edit" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% if not user.is_authenticated %}
<p class="alert alert-warning">
{% trans "<strong>Warning:</strong> You are not logged in. Your IP address will be logged." %}
<a href="{% url 'wiki:login' %}?next={% url 'wiki:edit' article_id=article.id path=urlpath.path %}">{% trans "Click here to log in" %} &raquo;</a>
</p>
{% endif %}

<div class="row">

  <div class="col-lg-8">
    <form method="POST" class="form-horizontal" id="article_edit_form">
      <input type="hidden" name="save" value="1" />
      <input type="hidden" name="preview" value="1" />
      {% with edit_form as form %}
        {% include "wiki/includes/editor.html" %}
      {% endwith %}
    </form>
  </div>

  <div class="col-lg-4" id="wiki-edit-sidebar">
    {% include "wiki/includes/editor_sidebar.html" %}
  </div>

</div>

<div style="clear: both"></div>

<div class="form-group form-actions">
  <div class="col-lg-8">
    <div class="col-lg-offset-2">
      <a class="btn btn-default" onclick="$('#previewModal').modal('show'); document.getElementById('article_edit_form').target='previewWindow'; document.getElementById('article_edit_form').action='{% url 'wiki:preview' path=urlpath.path article_id=article.id %}'; $('#article_edit_form').submit()" href="#">
        <span class="fa fa-eye"></span>
        {% trans "Preview" %}
      </a>
      <a class="btn btn-primary" onclick="window.onbeforeunload = null; document.getElementById('article_edit_form').target=''; document.getElementById('article_edit_form').action='{% url 'wiki:edit' path=urlpath.path article_id=article.id %}'; $('#article_edit_form').submit();" href="#">
        <span class="fa fa-check"></span>
        {% trans "Save changes" %}
      </a>
      {% if article|can_delete:user %}
      <a href="{% url 'wiki:delete' path=urlpath.path article_id=article.id %}" class="btn btn-danger pull-right">
        <span class="fa fa-trash-o"></span>
        {% trans "Delete article" %}
      </a>
      {% endif %}
    </div>
  </div>
</div>

{% include "wiki/includes/modals.html" %}

<div class="modal fade wiki-modal" id="previewModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <iframe name="previewWindow" frameborder="0"></iframe>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default btn-lg" data-dismiss="modal">
          <span class="fa fa-arrow-circle-left"></span>
          {% trans "Back to editor" %}
        </a>
        <a class="btn btn-lg btn-primary" onclick="window.onbeforeunload = null; document.getElementById('article_edit_form').target=''; document.getElementById('article_edit_form').action='{% url 'wiki:edit' path=urlpath.path article_id=article.id %}'; document.getElementById('article_edit_form').submit();" href="#">
          <span class="fa fa-check"></span>
          {% trans "Save changes" %}
        </a>
      </div>
    </div>
  </div>
</div>

{% addtoblock "js" %}
<script language="javascript">
  $(document).ready(function() {
    $("#article_edit_form :input").change(function() {
       $("#article_edit_form").data("changed",true);
    });
    if ($("#article_edit_form").find(".alert-danger").length > 0 || $("#article_edit_form").find(".has-error").length > 0 ) {
      // Set the forms status as "changed" if there was a submission error
      $("#article_edit_form").data("changed",true);
    }
    window.onbeforeunload = confirmOnPageExit;
  });

var confirmOnPageExit = function (e) {
  if ($("#article_edit_form").data("changed")) {
    e = e || window.event;
    var message = "You have unsaved changes!";
    // For IE6-8 and Firefox prior to version 4
    if (e) {
        e.returnValue = message;
    }
    // For Chrome, Safari, IE8+ and Opera 12+
    return message;
  } else {
    // If the form hasn't been changed, don't display the pop-up
    return;
  }
};
</script>
{% endaddtoblock %}

{% endblock %}

wiki/templates/wiki/history.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags static %}


{% block wiki_pagetitle %}{% trans "History" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% include "wiki/includes/modals.html" %}

{% addtoblock "js" %}
<script type="text/javascript" src="{% static "wiki/js/diffview.js" %}"></script>
<script type="text/javascript" src="{% static "wiki/js/diff.js" %}"></script>
{% endaddtoblock %}
{% addtoblock "css" %}
<style type="text/css">
  td.linenumber {
    width: 20px;
  }
  tr.insert td {
    background-color: #DFC;
  }
  tr.delete td {
    background-color: #FDC;
  }
  tr.equal td {
    background-color: #F2F2F2;
  }

  .diff-container td {
    white-space: pre; font-family: monospace;
  }
  .diff-container td,
  .diff-container th {
    padding: 2px 7px;
    border-right: 1px solid #DDD;
  }
  .diff-container td:last-child,
  .diff-container th:last-child {
    border-right: none;
  }
  .diff-container table {
    border-top: 1px solid #DDD;
  }
</style>
{% endaddtoblock %}

<p class="lead">
  {% trans "Click each revision to see a list of edited lines. Click the Preview button to see how the article looked at this stage. At the bottom of this page, you can change to a particular revision or merge an old revision with the current one." %}
</p>

<form method="GET">
  <div class="tab-content" style="overflow: visible;">
    {% for revision in revisions %}
      <div class="panel-group" id="accordion{{ revision.revision_number }}">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a class="panel-toggle" style="float: left;" href="#collapse{{ revision.revision_number }}" onclick="get_diff_json('{% url 'wiki:diff' revision.id %}', $('#collapse{{ revision.revision_number }}'))">
              {% if revision == article.current_revision %}
                <i class="fa fa-flag"></i>
              {% else %}
                <i class="fa fa-plus"></i>
              {% endif %}
              {% include "wiki/includes/revision_info.html" with current_revision=article.current_revision %}
              <div class="text-muted">
                <small>
                {% if revision.user_message %}
                  {{ revision.user_message }}
                {% elif revision.automatic_log %}
                  {{ revision.automatic_log }}
                {% else %}
                  ({% trans "no log message" %})
                {% endif %}
                </small>
              </div>
            </a>
            <div class="progress progress-striped active" style="display: none; width: 40px; float: left; margin-top: 7px; margin-bottom: -7px;">
              <div class="bar" style="width: 100%;"></div>
            </div>
            <div class="pull-right" style="vertical-align: middle; margin: 8px 8px;">
              {% if revision == article.current_revision %}
              <a href="#" class="btn btn-default disabled">
                <span class="fa fa-lock fa-fw"></span>
                {% trans "Preview this revision" %}
              </a>
              {% else %}
              <button type="submit" class="btn btn-default" onclick="$('#previewModal').modal('show'); this.form.target='previewWindow'; this.form.r.value='{{ revision.id }}'; this.form.action='{% url 'wiki:preview_revision' article.id %}'; $('#previewModal .switch-to-revision').attr('href', '{% url 'wiki:change_revision' path=urlpath.path article_id=article.id revision_id=revision.id %}')">
                <span class="fa fa-eye fa-fw"></span>
                {% trans "Preview this revision" %}
              </button>
              {% endif %}

              {% if article|can_write:user and not article.current_revision.locked %}
              <input type="radio"{% if revision == article.current_revision %} disabled="true"{% endif %} style="margin: 0 10px;" value="{{ revision.id }}" name="revision_id" switch-button-href="{% url 'wiki:change_revision' path=urlpath.path revision_id=revision.id %}" merge-button-href="{% url 'wiki:merge_revision_preview' article_id=article.id revision_id=revision.id %}" merge-button-commit-href="{% url 'wiki:merge_revision' path=urlpath.path article_id=article.id revision_id=revision.id %}" />
              {% endif %}

            </div>
            <div style="clear: both"></div>
          </div>
          <div id="collapse{{ revision.revision_number }}" class="panel-collapse collapse">
            <div class="panel-body diff-container" style="padding: 0;">
              <dl class="dl-horizontal">
                <dt>{% trans "Auto log:" %}</dt>
                <dd>{{ revision.automatic_log|default:"-"|linebreaksbr }}</dd>
              </dl>
              <table class="table table-condensed" style="margin: 0; border-collapse: collapse;">
                <thead>
                  <tr>
                    <th class="linenumber">{% if revision.previous_revision %}#{{revision.previous_revision.revision_number}}{% endif %}</th>
                    <th class="linenumber">#{{revision.revision_number}}</th>
                    <th>{% trans "Change" %}</th>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}

    {% include "wiki/includes/pagination.html" %}

    {% if revisions.count > 1 and article|can_write:user and not article.current_revision.locked %}

    <div class="form-group form-actions">
      <div class="pull-right">
        <button type="submit" name="preview" value="1" class="btn btn-default" onclick="$('#mergeModal').modal('show'); this.form.target='mergeWindow'; this.form.action=$('input[type=radio]:checked').attr('merge-button-href'); $('.merge-revision-commit').attr('href', $('input[type=radio]:checked').attr('merge-button-commit-href'))">
          <span class="fa fa-random"></span>
          {% trans "Merge selected with current..." %}
        </button>
        <button type="submit" name="save" value="1" class="btn btn-primary" onclick="this.form.target='_self'; this.form.action=$('input[type=radio]:checked').attr('switch-button-href')">
          <span class="fa fa-flag"></span>
          {% trans "Switch to selected version" %}
        </button>
      </div>
      <div style="clear:both"></div>
    </div>

    {% endif %}

  </div>
  <input type="hidden" name="r" value="" />
  <div class="modal fade wiki-modal" id="previewModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <iframe name="previewWindow" frameborder="0"></iframe>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default btn-lg" data-dismiss="modal">
            <span class="fa fa-arrow-circle-left"></span>
            {% trans "Back to history view" %}
          </a>
          {% if article|can_write:user %}
          <a href="#" class="btn btn-lg btn-primary switch-to-revision">
            <span class="fa fa-flag"></span>
            {% trans "Switch to this version" %}
          </a>
          {% else %}
            <a href="#" class="btn btn-lg btn-primary disabled">
              <span class="fa fa-lock"></span>
              {% trans "Switch to this version" %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade wiki-modal" id="mergeModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1>{% trans "Merge with current" %}</h1>
          <p class="lead"><span class="fa fa-info-circle"></span> {% trans "When you merge a revision with the current, all data will be retained from both versions and merged at its approximate location from each revision." %} <strong>{% trans "After this, it's important to do a manual review." %}</strong></p>
        </div>
        <div class="modal-body">
          <iframe name="mergeWindow" frameborder="0" style="min-height: 0;"></iframe>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default btn-lg" data-dismiss="modal">
            <span class="fa fa-arrow-circle-left"></span>
            {% trans "Back to history view" %}
          </a>
          {% if article|can_write:user %}
          <a href="#" class="btn btn-lg btn-primary merge-revision-commit">
            <span class="fa fa-file"></span>
            {% trans "Create new merged version" %}
          </a>
          {% else %}
            <a href="#" class="btn btn-lg btn-primary disabled">
              <span class="fa fa-lock"></span>
              {% trans "Create new merged version" %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock %}

wiki/templates/wiki/source.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Source of" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% if article.current_revision.locked %}
<p class="lead">{% trans "This article is currently locked for editing." %}</p>
{% endif %}

<pre class="pre-scrollable">
  {{ article.current_revision.content }}
</pre>

{% endblock %}